config/routes.rb
Mediamedoi::Application.routes.draw do
  resources :conversion_queue_items, :only => [:index]

  resources :media_libraries do
    collection do
      get :convert
    end
  end

  resources :hosts, :only => [:index]

end

app/models/media_library.rb
class MediaLibrary
  ROOT = Mediamedoi::Application.app_config[:media_library_root]
  
  def self.find_by_path(path)
    MediaLibraryDir.new(path)
  end
  
end

app/controllers/media_libraries_controller.rb
class MediaLibrariesController < ApplicationController
  
  def index
    @path = params[:path] || "/"
    @media_libraries = MediaLibrary.find_by_path(@path)

    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  def convert
    @path = params[:path]
    @media_library_file = MediaLibraryFile.new(@path)
    @conversion_queue_item = ConversionQueueItem.new_from_media_library_file(@media_library_file)
    @success = @conversion_queue_item.save!
    render :json => {:success => @success}
  end
  
end

app/helpers/media_libraries_helper.rb
module MediaLibrariesHelper
  def classes_for_media_library(media_library)
    classes = []
    classes << 'no_back' unless media_library.show_up_path?
    classes.join(' ')
  end
end

app/views/media_libraries/_media_library.html.haml
%ul.media_library_list.rounded
  - @media_libraries.entries.each do |file|
    - if file.directory?
      %li.directory{:data => file.to_html5_data}
        = link_to file.name, "#file_browser", 'data-path' => file.path
        %small.counter= file.entries_count
    -else
      %li.file{:data => file.to_html5_data}
        = link_to file.name, convert_media_libraries_path(:path => file.path)

app/views/media_libraries/index.html.haml
#wrapper
  .toolbar{:class => classes_for_media_library(@media_libraries)}
    %h1= @media_libraries.name
    = link_to 'Back', @media_libraries.up_path, :class => 'back'
    = link_to 'Queue', '#queue', :class => 'button'
  #file_browser
    = render 'media_library'
  
#queue
  .toolbar
    %h1= "Queue"
    = link_to 'Back', "#wrapper", :class => 'back'
  .ajax_target
    